function [net] = multitasknn_mnist_init_net(varargin)

rng('default');
rng(0) ;

f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct(...
    'name', 'input', ...
    'bottom', 'data', ...
    'top', {{'input', 'label1'}}, ...
    'type', 'data' ...
    ) ;
% 28 * 28 * 1
net.layers{end+1} = struct(...
    'name', 'conv1', ...
    'bottom', 'input', ...
    'top', 'conv1', ...
    'type', 'conv', ...
    'weights', {{f*randn(5,5,1,20, 'single'), zeros(1, 20, 'single')}}, ...
    'stride', 1, ...
    'pad', 2) ;
% 24 * 24 * 20

% 24 * 24 * 20

% 24 * 24 * 20

% 24 * 24 * 20
net.layers{end+1} = struct(...
    'name', 'conv3', ...
    'bottom', 'conv1', ...
    'top', 'conv3', ...
    'type', 'conv', ...
    'weights', {{f*randn(5,5,20,30, 'single'),zeros(1,30,'single')}}, ...
    'stride', 1, ...
    'pad', 2) ;
% 24 * 24 * 30
net.layers{end+1} = struct(...
    'name', 'conv5', ...
    'bottom', 'conv1', ...
    'top', 'conv5', ...
    'type', 'conv', ...
    'weights', {{f*randn(5,5,20,10, 'single'),zeros(1,10,'single')}}, ...
    'stride', 1, ...
    'pad', 2) ;
% 24 * 24 * 30
net.layers{end+1} = struct(...
    'name', 'concat1', ...
    'bottom', {{ 'conv3', 'conv5'}}, ...
    'top', 'concat1', ...
    'type', 'concat' ...
    ) ;

net.layers{end+1} = struct(...
    'name', 'conv4', ...
    'bottom', 'concat1', ...
    'top', 'conv4', ...
    'type', 'conv', ...
    'weights', {{f*randn(5,5,40,5, 'single'),  zeros(1,5,'single')}}, ...
    'stride', 1, ...
    'pad', 2) ;
net.layers{end+1} = struct(...
    'name', 'relu2', ...
    'bottom', 'conv4', ...
    'top', 'relu2', ...
    'type', 'relu'...
    ) ;
net.layers{end+1} = struct(...
    'name', 'fc1', ...
    'bottom', 'relu2', ...
    'top', 'fc1', ...
    'type', 'conv', ...
    'weights', {{f*randn(9,9,5,1, 'single'), zeros(1,1,'single')}}, ...
    'stride', 1, ...
    'pad', 4) ;
net.layers{end+1} = struct(...
    'name', 'loss1', ...
    'bottom', {{'fc1', 'label1'}}, ...
    'top', 'loss1', ...
    'type', 'euclideanloss') ;



end